version: '3.9'

services:
  redis:
    image: redis:latest
    tty: true
    ports:
      - '6379:6379'

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: True
    # command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - '8001:8000'
    depends_on:
      db:
        condition: service_healthy
#    env_file:
#      - .env

  celery:
    build: .
    tty: True
    command: celery -A config worker -l INFO
    depends_on:
      - redis
      - app

  celery-beat:
    build: .
    tty: True
    command: celery -A config beat -l INFO
    depends_on:
      - redis
      - app
      - celery

volumes:
  pg_data:
